FROM node:alpine

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

RUN npm run build

RUN adduser -u 1001 -D nodeuser && \
    chown -R nodeuser:nodeuser ./

USER nodeuser

CMD ["npm", "start"]