apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
        - name: static-website
          image: REPOSITORY/PROJECT_ID/IMAGE:TAG
---
apiVersion: v1
kind: Service
metadata:
  name: static-website-srv
spec:
  selector:
    app: static-website
  ports:
    - name: static-website
      protocol: TCP
      port: 80
      targetPort: 80
